services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev                 # Usa la etapa 'dev' del Dockerfile
    ports:
      - "5173:5173"    
    volumes:
      - .:/app
      - /usr/share/deviroment/container/fonts:/usr/share/fonts
      - /usr/share/deviroment/container/zsh-sudo/:/usr/share/zsh-sudo/
      - /usr/share/deviroment/container/powerlevel10k:/home/node/powerlevel10k # Tema de ZSH
      - /usr/share/deviroment/container/home/:/home/node/       # Monta configuraciones de usuario
    env_file:
      - .env                     # Variables de entorno desde archivo .env
    environment:
      NODE_ENV: development       
    command: >
        sh -c "tail -f /dev/null"
